INSERT INTO products (name, description, price, stock, image, category) VALUES
('Kemeja Flanel Kotak-Kotak', 'Kemeja flanel bahan katun lembut dan nyaman dipakai sehari-hari', 149000, 45, 'product.jpg', 'Pakaian'),
('Celana Chino Panjang', 'Celana chino pria model slim fit bahan stretch elastis', 185000, 30, 'product.jpg', 'Pakaian'),
('Kaos Polos Cotton Combed 30s', 'Kaos polos berbahan 100% cotton combed adem dan menyerap keringat', 45000, 100, 'product.jpg?text=Kaos+Polos', 'Pakaian'),
('Jaket Parka Waterproof', 'Jaket parka tahan air dan angin cocok untuk aktivitas outdoor', 275000, 20, 'product.jpg', 'Pakaian'),
('Sepatu Sneakers Casual', 'Sepatu sneakers gaya trendi dengan insole empuk', 299000, 25, 'product.jpg', 'Sepatu'),
('Sepatu Lari Running Shoes', 'Sepatu lari ringan dengan sirkulasi udara baik', 350000, 15, 'product.jpg', 'Sepatu'),
('Sandal Gunung Outdoor', 'Sandal gunung dengan daya cengkeram kuat dan tali tahan putus', 120000, 40, 'product.jpg', 'Sepatu'),
('Tas Ransel Laptop 15 Inch', 'Tas ransel kompartemen luas dilengkapi slot laptop berbusa', 210000, 35, 'product.jpg', 'Aksesoris'),
('Dompet Kulit Pria', 'Dompet kulit sintetis elegan dengan banyak slot kartu', 75000, 50, 'product.jpg', 'Aksesoris'),
('Jam Tangan Analog Sport', 'Jam tangan tahan air hingga 30m dengan bezel stainless steel', 320000, 18, 'product.jpg', 'Aksesoris'),
('Topi Baseball Polos', 'Topi baseball bahan rapel tebal dengan pengatur ukuran belakang', 35000, 60, 'product.jpg', 'Aksesoris'),
('Headphone Wireless Bluetooth', 'Headphone dengan bass mantap dan ketahanan baterai hingga 20 jam', 285000, 22, 'product.jpg', 'Elektronik'),
('Earphone TWS Bluetooth 5.3', 'Earphone nirkabel latensi rendah cocok untuk game dan musik', 159000, 40, 'product.jpg', 'Elektronik'),
('Smartwatch Sport Tracker', 'Jam tangan pintar pemantau detak jantung dan langkah kaki', 450000, 12, 'product.jpg', 'Elektronik'),
('Powerbank 10000mAh Fast Charging', 'Powerbank pengisian cepat dual output USB dan Type-C', 175000, 55, 'product.jpg', 'Elektronik'),
('Speaker Bluetooth Portable', 'Speaker mini suara kencang tahan percikan air', 135000, 28, 'product.jpg', 'Elektronik'),
('Mouse Wireless Silent Click', 'Mouse nirkabel tanpa suara klik dengan sensitivitas tinggi', 85000, 48, 'product.jpg', 'Elektronik'),
('Keyboard Mechanical RGB', 'Keyboard gaming mechanical switch biru dengan lampu RGB', 399000, 14, 'product.jpg', 'Elektronik'),
('Stand Laptop Aluminium', 'Stand laptop ergonomis bahan aluminium tebal bisa dilipat', 115000, 30, 'product.jpg', 'Aksesoris'),
('Kipas Angin Mini USB', 'Kipas angin portabel dapat diisi ulang dengan kabel USB', 40000, 70, 'product.jpg', 'Elektronik'),
('Botol Minum Termos Stainless', 'Termos air 500ml menjaga suhu panas dan dingin hingga 12 jam', 65000, 80, 'product.jpg', 'Peralatan Rumah'),
('Cangkir Keramik Estetik', 'Cangkir kopi bahan keramik tebal dengan desain minimalis', 38000, 45, 'product.jpg', 'Peralatan Rumah'),
('Wajan Anti Lengket Teflon', 'Wajan penggorengan diameter 24cm lapisan anti lengket', 125000, 25, 'product.jpg', 'Peralatan Rumah'),
('Panci Stainless Steel', 'Panci masak serbaguna dilengkapi tutup kaca transparan', 145000, 20, 'product.jpg', 'Peralatan Rumah'),
('Pisau Dapur Set 5 in 1', 'Set pisau dapur tajam berbahan stainless steel anti karat', 95000, 33, 'product.jpg', 'Peralatan Rumah'),
('Sapu dan Pengki Set', 'Set sapu plastik dan pengki dengan gagang panjang ergonomis', 48000, 50, 'product.jpg', 'Peralatan Rumah'),
('Handuk Mandi Dewasa Katun', 'Handuk mandi daya serap tinggi ukuran 70x140 cm', 79000, 65, 'product.jpg', 'Peralatan Rumah'),
('Sprei Katun Polos Ukuran 160x200', 'Sprei bahan katun mikro halus tidak luntur dan tidak berbulu', 110000, 22, 'product.jpg', 'Peralatan Rumah'),
('Bantal Kepala Silicon', 'Bantal tidur empuk isi serat silikon tidak mudah kempes', 55000, 40, 'product.jpg', 'Peralatan Rumah'),
('Lampu Meja Belajar LED', 'Lampu meja belajar rechargeable dengan 3 tingkat kecerahan', 72000, 38, 'product.jpg', 'Elektronik'),
('Kopi Bubuk Arabika 250g', 'Kopi bubuk murni kualitas premium aroma harum segar', 68000, 90, 'product.jpg', 'Makanan & Minuman'),
('Teh Hijau Celup Organik', 'Teh hijau kaya antioksidan kemasan isi 25 kantong teh', 25000, 110, 'product.jpg', 'Makanan & Minuman'),
('Madu Murni Asli 500ml', 'Madu hutan murni tanpa campuran bahan pengawet', 98000, 35, 'product.jpg', 'Makanan & Minuman'),
('Cokelat Batangan Dark Chocolate', 'Cokelat hitam 70% kakao rasanya mantap dan sehat', 32000, 75, 'product.jpg', 'Makanan & Minuman'),
('Keripik Kentang Original 100g', 'Camilan keripik kentang renyah bumbu gurih alami', 18000, 120, 'product.jpg', 'Makanan & Minuman'),
('Minyak Zaitun Extra Virgin 250ml', 'Minyak zaitun murni bagus untuk memasak dan perawatan kulit', 85000, 28, 'product.jpg', 'Makanan & Minuman'),
('Sabun Cuci Muka Face Wash', 'Pembersih wajah untuk mengontrol minyak berlebih dan jerawat', 35000, 60, 'product.jpg', 'Kecantikan'),
('Sunscreen SPF 50 PA++++', 'Tabir surya tekstur ringan tidak lengket di kulit', 62000, 45, 'product.jpg', 'Kecantikan'),
('Serum Wajah Vitamin C', 'Serum pencerah kulit dan penyamar noda hitam', 89000, 30, 'product.jpg', 'Kecantikan'),
('Pelembab Moisturizer Gel', 'Gel pelembab wajah formula cepat meresap dan menghidrasi', 54000, 50, 'product.jpg', 'Kecantikan'),
('Shampoo Anti Ketombe 300ml', 'Shampoo pembersih kulit kepala dan pembasmi ketombe', 42000, 70, 'product.jpg', 'Kecantikan'),
('Sabun Mandi Cair Refill 450ml', 'Sabun mandi cair wewangian bunga menyegarkan', 28000, 85, 'product.jpg', 'Kecantikan'),
('Matras Yoga Non-Slip 6mm', 'Matras olahraga fleksibel tahan licin bahan TPE', 135000, 19, 'product.jpg', 'Olahraga'),
('Dumbbell Karet 5kg', 'Barbel beban karet 5kg aman digunakan untuk latihan di rumah', 95000, 24, 'product.jpg', 'Olahraga'),
('Tali Skipping Jump Rope', 'Tali lompat berbahan kabel baja adjustable dengan bearing halus', 35000, 80, 'product.jpg', 'Olahraga'),
('Bola Basket Size 7', 'Bola basket bahan kulit sintetis cocok untuk indoor dan outdoor', 180000, 15, 'product.jpg', 'Olahraga'),
('Kacamata Renang Anti Fog', 'Kacamata renang dengan lapisan anti embun dan pelindung UV', 65000, 33, 'product.jpg', 'Olahraga'),
('Buku Catatan Notebook A5', 'Buku tulis garis isi 80 lembar kertas tebal anti tembus', 22000, 150, 'product.jpg', 'Alat Tulis'),
('Pulpen Gel Hitam Box isi 12', 'Pulpen gel tinta lancar dan cepat kering ukuran 0.5mm', 28000, 100, 'product.jpg', 'Alat Tulis'),
('Pensil Warna 24 Warna', 'Set pensil warna tidak mudah patah pigmen warna pekat', 45000, 40, 'product.jpg', 'Alat Tulis');